fix test errors: ./src/app/routes/user/home/home.component.spec.ts:5:0-80 - Error: Module not found: Error: Can't resolve '@app/authenticated/user/home/home.component' in '/home/runner/work/OnlineVotingSystem_Frontend/OnlineVotingSystem_Frontend/src/app/routes/user/home'
Error: src/app/core/guards/auth/auth.guard.spec.ts:42:44 - error TS2345: Argument of type 'Promise<ApiAuthResponse>' is not assignable to parameter of type 'Observable<ApiAuthResponse | ApiAuthErrorResponse>'.
  Type 'Promise<ApiAuthResponse>' is missing the following properties from type 'Observable<ApiAuthResponse | ApiAuthErrorResponse>': source, operator, lift, subscribe, and 3 more.

42   authService.isTokenValid.and.returnValue(Promise.resolve(response));