bugfix/authentication testing errors, unified the login process by merging the otp and login pages (#84)
Verbose commit logs:


* added otp integration and fix some bugs

* used observable on other auth endpoints and added logout session feature (not fully functional)

* added routes and component for the following:
new vote
new election

added pop up bar for adding new vote
enhance responsiveness of the home component
added filter nav

* added poll options low level logic

* added dynamic routes for poll id handling
added service responsible for adding, modifying and updating polls

* restructure to adhere with singleton and best practice file structure convention

* removed redundant images

* feat: migration to scss and switching to scss

* migrated the home page to scss

* simplified the sign up form group

* fix form group issues

* added nat error inside the mat-form-field for error handling to reduce reliance on the snackbar.

* refactor:
environment variables (add v1 prefix)
removed remnant classes
use dependency injection instead of constructor injection
create reusable auth-form sass file for better reusability
added images for auth forms
added new mixin functions and variables

* - removed remnant styles and classnames in home page
- fix verify email bug on loading
- refactor forgot password page
- clarity on the otp component form
- fix mat-error not showing
- refactor verify email page
- uses DI Injection on verify email component

* change font set in the index.html and trimmed some css as the issue budgeting warning occurs

* change code style in the auth guard and fix the issue when building the app causes ecconreset due to api call (inadvertently during build process)

* implements lazy loading and remove unnecessary dependencies and implements tree shaking

* fix test errors:
./src/app/routes/user/home/home.component.spec.ts:5:0-80 - Error: Module not found: Error: Can't resolve '@app/authenticated/user/home/home.component' in '/home/runner/work/OnlineVotingSystem_Frontend/OnlineVotingSystem_Frontend/src/app/routes/user/home'

Error: src/app/core/guards/auth/auth.guard.spec.ts:42:44 - error TS2345: Argument of type 'Promise<ApiAuthResponse>' is not assignable to parameter of type 'Observable<ApiAuthResponse | ApiAuthErrorResponse>'.
  Type 'Promise<ApiAuthResponse>' is missing the following properties from type 'Observable<ApiAuthResponse | ApiAuthErrorResponse>': source, operator, lift, subscribe, and 3 more.

42   authService.isTokenValid.and.returnValue(Promise.resolve(response));

* fix some tests issues

* rectify the issues on test particularly on edit poll component

* fix errors on validation of the sign up form

* enhance login flow code and remove redundant validator service (idk why i created those in the first place)

* fix missing modules bugs

* testing: trying to fix auth guard and edit poll tests failures

* style: add SCSS styles for user home and filter navigation components

* uncomment the lines necessary in the auth guards

* migrate other pages to sass

* migrate user and admin pages to sass

* test: update EditPollComponent tests to use mock data and jasmine spies

* fix: update PollService to return undefined for non-existent polls and enhance EditPollComponent tests with a PollService spy

* fix: improve error handling in PollService and update EditPollComponent tests for better coverage

* improvements: refactor unified login page and add manage polls route in admin(#96)

Verbose commit logs:

* refactor: update auth guard and navbar components, remove OTP component and related tests

* feat: add resend OTP functionality and improve login component UI

* feat: implement personal information and password change forms in settings component

* feat: remove voting instructions component and update navbar to open dialog for instructions

* feat: add Manage Polls component and update navbar for navigation

* feat: add Manage Polls route and component, update navbar for navigation

* fix tests errors (#98)

* test: enhance ManageUsersComponent and DialogBoxComponent tests with additional imports and assertions

* test: simplify DialogBoxComponent tests by removing unnecessary imports and adding basic assertions